image: node:latest
before_script:
 - apt-get update -qy
 - apt-get install -y postgresql-client
 - cd app
stages:
  - install
  - build
  - test
  - deploy
install:
  stage : install 
  script:
    - npm install
    - npm install glob rimraf
    - npm i -g typeorm ts-node
  tags:
    - "runner"
build:
  stage: build
  tags:
    - "runner"
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
     - build/
test:
  tags:
    - "runner"
  stage: test
  script:
    - npm test
    - npm run lint
