image: node:latest
before_script:
 - apt-get update -qy
 - apt-get install -y postgresql-client
 - cd app
stages:
  - install
  - build
  - test
  - deploy
install:
  stage : install 
  script:
    - npm install
    - npm install glob rimraf jest-cli
    - npm i -g typeorm ts-node
  tags:
    - "runner"
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
build:
  stage: build
  tags:
    - "runner"
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
     - build
test:
  tags:
    - "runner"
  stage: test
  script:
    - npm test
    - npm run lint
