image: node:fermium-alpine
stages:
 - build
 - test
 - deploy
build:
  stage: build
  script:
    - cd app
    - npm install
    - npm run build
  artifacts:
    paths:
     - build/
test:
  stage: test
  script:
    - cd app
    - npm test
    - npm run lint
